DROP TABLE IF EXISTS SUPPORT;

CREATE TABLE COMMENT (
id INT AUTO_INCREMENT  PRIMARY KEY,
firstname VARCHAR(50) NOT NULL,
lastname VARCHAR(50) NOT NULL,
phone VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
comment VARCHAR(200) NOT NULL
);